CREATE TABLE IF NOT EXISTS public.comscore_data (
    property_name TEXT,
    display_name TEXT,
    is_network BOOLEAN,
    parent_network TEXT,
    segments TEXT,
    report_month DATE,
    month_label TEXT,
    year INTEGER,
    month_num INTEGER,
    quarter INTEGER,
    quarter_label TEXT,
    financial_year TEXT,
    unique_users NUMERIC,
    prev_month_uu NUMERIC,
    prev_quarter_uu NUMERIC,
    prev_year_uu NUMERIC,
    mom_pct NUMERIC,
    mom_abs NUMERIC,
    qoq_pct NUMERIC,
    qoq_abs NUMERIC,
    yoy_pct NUMERIC,
    yoy_abs NUMERIC,
    rank_in_segment NUMERIC,
    data_source TEXT,
    load_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);